### ISSUE TITLE
Don't run is there's another instance already running

### ISSUE THREAD

**Issue by Sacules** [Sacules/ms#7]
Sometimes I forget I already have `ms` running and accidentally overwrite the current queue with an outdated one. A simple solution would be creating an empty `ms.lock` file when starting, and delete it before exiting. You'd just need to check that it exists right when starting, and exit if it does.

**Comment by TotallyNotChase** [comment]
Hello, I'd like to take this on.

To start, I'd like to ask a few questions, Should I create a ms.lock file when main.go is executed or when Tui.go is executed?

Finally, For exiting, I believe you'd need to delete the file in any and all code with exit() functions, or equivalent. Could you tell me which functions you are using to exit the program other than exit?

**Comment by Sacules** [comment]
Hi, you should check for the lock file and create it if it doesn't exist right at the beginning of the main function.

It's not necessary to look for all the functions that exit the program, just `defer` the deletion of the file once it's created.

**Comment by TotallyNotChase** [comment]
Thanks! I think using signals instead of defer is better though. If your program is terminated unusually by the OS `defer` won't be reached so I advocate using signals.

I'm currently working on debugging it correctly, can you tell me if just doing `os.Create("ms.lock")` and then `os.Remove("ms.lock")1 is fine for you? 

Sources : 
-  [Why defer is a bad idea for important files?](https://stackoverflow.com/questions/41432193/how-to-delete-a-file-using-golang-on-program-exit)

- [How to use signals in golang?](https://gobyexample.com/signals)

**Comment by TotallyNotChase** [comment]
Alright so I'm done with adding both a defer and a signal removal but I'm not able to test it correctly.

It looks like when I run `ms.exe` after I run `go build` in the terminal the console just starts and immediately closes, any idea why? I'm trying the original version of your repo, without any of my modifications.

**Comment by Sacules** [comment]
I like the idea of implementing signals, go for it as long as you can keep it simple :)

It seems you're running on Windows, right? It's speculation, but I think the root issue is that the current default path for saving the queue is `$XDG_DATA_HOME/ms/current.json`, which is pretty much a Unix-only path, so I'm not sure where it's trying to save to on Windows. I've just pushed a branch (`config-path`) to test on other platforms. Please try it with `ms newblock` to check if it works properly, and then we can try to keep working in the lock file.
